### ISSUE TITLE
rss feed?

### ISSUE THREAD

**Issue by jarrodu** [felixmulder/felixmulder.github.io#1]
Do you have an RSS feed for your blog?

**Comment by felixmulder** [comment]
I don't - but maybe I should :)

**Comment by felixmulder** [comment]
Added the feed plugin now. Does that work for you?

**Comment by jarrodu** [comment]
Almost! It is a valid RSS feed. But what about your talks? That is where most of your content is. Maybe a quick blog post with a summary of each new talk. That way they show up in your RSS feed.

But that sounds like more work. ;-) It is of course up to you.

**Comment by jarrodu** [comment]
Oh and thanks for add the RSS!

**Comment by felixmulder** [comment]
I'll try to get around to it sometime in the near future, but for now cba ;)

Thanks for the suggestion!
